# Generated by Django 3.2.4 on 2021-07-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('matricula_mobiliaria', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True, verbose_name='Matrícula inmobiliaria')),
                ('cedula_catastral', models.CharField(max_length=100, unique=True, verbose_name='Cédula catastral')),
                ('direccion', models.CharField(max_length=150, verbose_name='Dirección')),
                ('tipo_predio', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Urbano'), (2, 'Rural')], default=3, null=True, verbose_name='Tipo de predio')),
            ],
            options={
                'verbose_name': 'Predio',
                'verbose_name_plural': 'Predios',
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('identificacion', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Identificación')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del propietario')),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Persona'), (2, 'Empresa')], default=3, null=True)),
                ('predios', models.ManyToManyField(to='predios.Predio')),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
            },
        ),
    ]
